FROM python

WORKDIR /workspace/yomigana-ebook

# tell git the project directory is safe
RUN git config --global --add safe.directory /workspace/yomigana-ebook

# install poetry
RUN curl -sSL https://install.python-poetry.org | python3 -
ENV PATH="/root/.local/bin:$PATH"
RUN poetry self update
